---
name: "Nix build"
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-24.04, target: x86_64-linux }
          - { os: macos-13, target: x86_64-darwin }
          - { os: macos-14, target: aarch64-darwin }
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build package
      run: nix build ".#packages.${{matrix.job.target}}.default" -Lv --accept-flake-config
      shell: bash
    - name: Build devShell
      run: nix build ".#devShells.${{matrix.job.target}}.default" -Lv --accept-flake-config
      shell: bash
